<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2023 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
/**
 * @var \Tigren\Portfolio\Block\Display $block
 */

//echo $block->categoryShow();


?>
<textarea name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Comment')) ?>" class="input-text"
          data-mage-init='{"Tigren_Portfolio/js/kiwicount": {"maxlen":"150","messagebox":"charNum"}
}'></textarea>

<script type="text/x-magento-init">
{
    "#my-element": {
        "myCustomData": {
            "foo": "bar",
            "baz": 123
        }
    }
}


</script>

<span id="charNum"></span>
<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    .post-id {
        width: 2%
    }

    .post-name {
        width: 30%
    }

</style>

<table>
    <tr>
        <th class="category-name">Name</th>
        <th>Identifier</th>
    </tr>
    <?php
    foreach ($block->getPostCollection() as $key => $category) {
        echo '<tr>
                    <td>' . $category->getCategoryName() . '</td>
                    <td>' . $category->getIdentifier() . '</td>
                  </tr>';
    }
    ?>
</table>

</body>

</html>

