<?php

/**
 * @var \Tigren\Portfolio\Block\DisplayDetails $block
 */

echo $block->DetailsShow();

?>

<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    .post-id {
        width: 2%
    }

    .post-name {
        width: 30%
    }

</style>

<table>
    <tr>
        <th class="portfolio-id">Portfolio Id</th>
        <th class="name">Name</th>
        <th class="identifier">Identifier</th>
        <th>Identifier</th>
    </tr>
    <?php
    foreach ($block->getPostCollection() as $key => $details) {
        echo '<tr>
                    <td>' . $details->getPortfolioId() . '</td>
                    <td>' . $details->getName() . '</td>
                    <td>' . $details->getIdentifier() . '</td>
                  </tr>';
    }
    ?>
</table>

</body>
</html>
