<!--the content of the block's message(code challenge 1)-->
<p>WELCOME TO TIGREN SOLUTIONS</p>

<?php
/**
 * @author    Tigren Solutions <info@tigren.com>
 * @copyright Copyright (c) 2023 Tigren Solutions <https://www.tigren.com>. All rights reserved.
 * @license   Open Software License ("OSL") v. 3.0
 */
/** @var Magento\Framework\View\Element\Template $block */
?>
<!--Challenge 2-->
<?= $block->getChildHtml('my.custom.block.child') ?>
