<div id="delivery-date">
    <!-- @author    Tigren Solutions <info@tigren.com>-->
    <!-- @copyright Copyright (c) 2023 Tigren Solutions <https://www.tigren.com>. All rights reserved.-->
    <!-- @license   Open Software License ("OSL") v. 3.0-->
    <strong><?= __('Delivery Date') ?></strong>
    <span class="price"><?= $block->getDeliveryDate() ?></span>
</div>
<div id="delivery-comment">
    <strong><?= __('Comment') ?>:</strong>
    <br />
    <span class="price"><?= $block->getDeliveryComment() ?></span>
</div>
<script type="text/javascript">
    require(
        ['jquery'],
        function ($) {
            var element = $('#delivery-date').detach();
            $('.box-order-shipping-method').append(element);
            var element = $('#delivery-comment').detach();
            $('.box-order-shipping-method').append(element);
        }
    );
</script>
